### ISSUE TITLE
Can I use this repo to download M3U8 HLS and save in local disk?

### ISSUE THREAD

**Issue by zydjohnHotmail** [yoyokits/VideoBrowser#21]
Hello:
I want to know if I can use this repo to download HLS, which has the following format:
https://video1.maxline.by:444/o1/stream05/playlist.m3u8
It is a live sports game in HLS, the link will expire in 2 hours.
And save as a MP4 format video in local disk?
Thanks,

**Comment by yoyokits** [comment]
I am sorry for late response, but this version can  only for youtube.
You can try to visit youtube-dl official website that probably can download it.
